### ISSUE TITLE
[Question] How do I get started? 

### ISSUE THREAD

**Issue by vsmart** [rogerallen/explore_overtone#6]
Hi, 

Thanks for collecting and providing these examples - they are diverse and very cool! 
I'm looking at the maze example specifically. Excuse my possibly silly question, but: how would I go about "running" that code? It's not its own namespace so I couldn't find a way to load in a repl, aside from copy pasting each function into it. What is the starting point? 

Thank you & thanks for taking care of this repo! 

Fran

**Comment by rogerallen** [comment]
Thanks for the note.  I'm glad you like the examples.

That maze example is one from very early in my Clojure experience.  I probably was copy-pasting into the repl at this point, just as you had to do.  Yes, it should have a namespace--if you make it work send on a pull request.  :smile_cat:

**Comment by vsmart** [comment]
Thanks for your reply :) I'll see if I get a chance to dive into the examples again. By the way, we have a clojure art group in Berlin and we're all big fans of your work with the tweegeemee bot too!

**Comment by rogerallen** [comment]
Thanks!  :smile:
